post_install() {
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
	ln -s /usr/share/ente_auth/ente_auth /usr/bin/ente_auth
	chmod +x /usr/bin/ente_auth
	update-desktop-database -q
	ln -s /usr/lib/libsodium.so /usr/lib/libsodium.so.23
}

post_upgrade() {
	post_install
}

post_remove() {
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
	rm /usr/bin/ente_auth
	update-desktop-database -q
	rm /usr/lib/libsodium.so.23
}
